### ISSUE TITLE
有没有 导入数据库的脚本

### ISSUE THREAD

**Issue by zwd13122889** [wysheng/kindergarten#3]

**Comment by Lu-dashuai** [comment]
这项目直接部署就可以运行呀




看到请及时回复，3Q!
在2020年05月12日 15:12，zwd13122889 写道：

**Comment by Lu-dashuai** [comment]
加我qq我帮你弄




看到请及时回复，3Q!
在2020年05月12日 15:12，A芦瑞华i-Do. 写道：
这项目直接部署就可以运行呀




看到请及时回复，3Q!
在2020年05月12日 15:12，zwd13122889 写道：

**Comment by Lu-dashuai** [comment]
970638341




看到请及时回复，3Q!
在2020年05月12日 15:13，A芦瑞华i-Do. 写道：
加我qq我帮你弄




看到请及时回复，3Q!
在2020年05月12日 15:12，A芦瑞华i-Do. 写道：
这项目直接部署就可以运行呀




看到请及时回复，3Q!
在2020年05月12日 15:12，zwd13122889 写道：

**Comment by zwd13122889** [comment]
> 970638341 看到请及时回复，3Q! 在2020年05月12日 15:13，A芦瑞华i-Do. 写道： 加我qq我帮你弄 看到请及时回复，3Q! 在2020年05月12日 15:12，A芦瑞华i-Do. 写道： 这项目直接部署就可以运行呀 看到请及时回复，3Q! 在2020年05月12日 15:12，zwd13122889 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，稍微 晚一点  我现在在上课。

**Comment by zwd13122889** [comment]
> 970638341 看到请及时回复，3Q! 在2020年05月12日 15:13，A芦瑞华i-Do. 写道： 加我qq我帮你弄 看到请及时回复，3Q! 在2020年05月12日 15:12，A芦瑞华i-Do. 写道： 这项目直接部署就可以运行呀 看到请及时回复，3Q! 在2020年05月12日 15:12，zwd13122889 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

老哥  可以了吗

**Comment by Lu-dashuai** [comment]
你是提莫吗？




看到请及时回复，3Q!
在2020年05月12日 16:15，zwd13122889 写道：

970638341 看到请及时回复，3Q! 在2020年05月12日 15:13，A芦瑞华i-Do. 写道： 加我qq我帮你弄 看到请及时回复，3Q! 在2020年05月12日 15:12，A芦瑞华i-Do. 写道： 这项目直接部署就可以运行呀 看到请及时回复，3Q! 在2020年05月12日 15:12，zwd13122889 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

老哥 可以了吗

**Comment by zwd13122889** [comment]
牛皮牛皮
